version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app:delegated
      - /app/ui/node_modules
      - /app/ui/dist

  redis:
    image: redis:7-alpine
    ports:
      - "63798:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 