version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app:delegated
      - /app/static/node_modules
      - /app/static/dist
    command: sh -c "cd /app/static && npm install && npm run build && cd /app && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  redis:
    image: redis:7-alpine
    ports:
      - "63798:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: 